version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: greenquote
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build: .
    restart: on-failure
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/greenquote
      JWT_SECRET: replace-me
      JWT_EXPIRES_IN: 3600s
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "npm run prisma:generate && npx prisma migrate deploy || npm run prisma:migrate && npm run prisma:seed && npm run start"

volumes:
  db-data:
